apiVersion: v1
kind: ConfigMap
metadata:
  name: alloul-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'alloul-api'
        static_configs:
          - targets: ['alloul-api:4000']
        metrics_path: /v1/observability/metrics
