apiVersion: v1
kind: Service
metadata:
  name: alloul-api
  namespace: alloul-one
spec:
  selector:
    app: alloul-api
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
