apiVersion: v1
kind: Service
metadata:
  name: alloul-web
  namespace: alloul-one
spec:
  selector:
    app: alloul-web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
