apiVersion: v1
kind: Secret
metadata:
  name: alloul-secrets
  namespace: alloul-one
type: Opaque
stringData:
  DATABASE_URL: ""
  REDIS_URL: ""
  JWT_SECRET: ""
  STRIPE_WEBHOOK_SECRET: ""
  OIDC_CLIENT_ID: ""
  OIDC_CLIENT_SECRET: ""
